name: QoLMechanics
version: '${version}'

main: im.apeki.qolmechanics.QoLMechanicsPlugin
api-version: '1.20'
load: POSTWORLD

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.3.20

commands:
  qol: